[package]
name = "sniffnet-packet-parser"
version = "0.2.0"
description = "Network packet parser for Sniffnet"
readme = "README.md"
keywords = ["network", "packet", "sniffer", "parser", "pcap"]
categories = ["parser-implementations", "network-programming"]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["full"]
# without this only `Protocol` is available
# (needed in sniffnet's build.rs for cross-compilation without pcap)
full = ["dep:etherparse", "dep:pcap"]

[dependencies]
etherparse = { workspace = true, optional = true }
pcap = { workspace = true, optional = true }

[lints]
workspace = true

[badges]
maintenance = { status = "actively-developed" }
